services:
  php_laravel_example:
    build: ./php
    container_name: php_$PROJECT_NAME
    volumes:
      - ../:/code
      - ./php:/usr/local/etc/php
      - /tmp:/tmp
    ports:
      - "$PHP_PORT:9000"
    expose:
      - "$PHP_PORT"
    networks:
      laravel_example:
        ipv4_address: 10.7.0.7
    depends_on:
      - mysql_laravel_example
      - redis_laravel_example
  nginx_laravel_example:
    image: nginx:latest
    container_name: nginx_$PROJECT_NAME
    ports:
      - "$NGINX_PORT:80"
    expose:
      - "$NGINX_PORT"
    volumes:
      - ../:/code
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      laravel_example:
        ipv4_address: 10.7.0.5
    depends_on:
      - php_laravel_example
  mysql_laravel_example:
      image: mariadb:latest
      container_name: mysql_$PROJECT_NAME
      command: --default-authentication-plugin=mysql_native_password && mysqladmin -u root -p status
      restart: always
      ports:
          - "$MYSQL_PORT:3306"
      expose:
          - "$MYSQL_PORT"
      environment:
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
          - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
          - MYSQL_TCP_PORT:${MYSQL_PORT}
      networks:
          laravel_example:
              ipv4_address: 10.7.0.6
  redis_laravel_example:
      image: redis:latest
      container_name: redis_$PROJECT_NAME
      ports:
          - "$REDIS_PORT:80"
      expose:
          - "$REDIS_PORT"
      networks:
          laravel_example:
              ipv4_address: 10.7.0.10
networks:
  laravel_example:
    driver: bridge
    ipam:
      config:
        - subnet: 10.7.0.0/16
          gateway: 10.7.0.1
